export default function Head() {
  return (
    <>
      <title>Study NextJS 13</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
